// Generated by purs bundle 0.13.8
var PS = {};
(function(exports) {
  "use strict";

  exports.log = function (s) {
    return function () {
      console.log(s);
      return {};
    };
  };
})(PS["Effect.Console"] = PS["Effect.Console"] || {});
(function($PS) {
  // Generated by purs version 0.13.8
  "use strict";
  $PS["Effect.Console"] = $PS["Effect.Console"] || {};
  var exports = $PS["Effect.Console"];
  var $foreign = $PS["Effect.Console"];
  exports["log"] = $foreign.log;
})(PS);
(function($PS) {
  // Generated by purs version 0.13.8
  "use strict";
  $PS["Main"] = $PS["Main"] || {};
  var exports = $PS["Main"];
  var Effect_Console = $PS["Effect.Console"];
  var main = Effect_Console.log("Hello, Diamond!!\u2764\ufe0f");
  exports["main"] = main;
})(PS);
PS["Main"].main();

/*Toggle dropdown list*/
/*https://gist.github.com/slavapas/593e8e50cf4cc16ac972afcbad4f70c8*/

var navMenuDiv = document.getElementById("nav-content");
var navMenu = document.getElementById("nav-toggle");

document.onclick = check;
function check(e){
  var target = (e && e.target) || (event && event.srcElement);

  //Nav Menu
  if (!checkParent(target, navMenuDiv)) {
  // click NOT on the menu
  if (checkParent(target, navMenu)) {
    // click on the link
    if (navMenuDiv.classList.contains("hidden")) {
    navMenuDiv.classList.remove("hidden");
    } else {navMenuDiv.classList.add("hidden");}
  } else {
    // click both outside link and outside menu, hide menu
    navMenuDiv.classList.add("hidden");
  }
  }

}

function checkParent(t, elm) {
  while(t.parentNode) {
  if( t == elm ) {return true;}
  t = t.parentNode;
  }
  return false;
}

var htmlDoc = document.documentElement;
var checkboxA = document.getElementById('toggleA');
var checkboxB = document.getElementById('toggleB');

initDarkMode();

checkboxA.addEventListener('change', flipDarkMode);
checkboxB.addEventListener('change', flipDarkMode);

function flipDarkMode () {
  console.log('Wonderboy');
  localStorage.darkMode = this.checked;
  console.log(localStorage.darkMode);
  if (localStorage.darkMode === 'true') {
    htmlDoc.classList.add('mode-dark');
    checkboxA.checked = true;
    checkboxB.checked = true;
    console.log('dark');
  } else if (localStorage.darkMode === 'false') {
    htmlDoc.classList.remove('mode-dark');
    checkboxA.checked = false;
    checkboxB.checked = false;
    console.log('light')
  }
}

function initDarkMode () {
  console.log("Init Dark Mode")
  if (localStorage.darkMode === 'true') {
    console.log("initDarkMode is True")
    htmlDoc.classList.add('mode-dark');
    checkboxA.checked = true;
    checkboxB.checked = true;
  } else if (localStorage.darkMode === 'false') {
    console.log("initDarkMode is false")
    htmlDoc.classList.remove('mode-dark');
    checkboxA.checked = false;
    checkboxB.checked = false;
  } else {
    console.log("initDarkMode is null")
    htmlDoc.classList.remove('mode-dark');
    checkboxA.checked = false;
    checkboxB.checked = false;
  }
}
